# Generated by Django 5.2.5 on 2025-08-13 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0010_multi_club_membership_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('intended_role', models.CharField(default='rider', max_length=20, verbose_name='Rol previsto')),
                ('personal_message', models.TextField(blank=True, help_text='Mensaje del padrino', verbose_name='Mensaje personal')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('declined', 'Rechazada'), ('expired', 'Expirada')], default='pending', max_length=10, verbose_name='Estado')),
                ('expires_at', models.DateTimeField(verbose_name='Expira el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceptada el')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='clubs.chapter')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='clubs.club')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invitado por')),
                ('member', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='clubs.member')),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
                'ordering': ['-created_at'],
                'unique_together': {('email', 'club', 'status')},
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado el')),
                ('success', models.BooleanField(default=True, verbose_name='Exitoso')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='emails.invitation')),
            ],
            options={
                'verbose_name': 'Log de Email',
                'verbose_name_plural': 'Logs de Emails',
                'ordering': ['-sent_at'],
            },
        ),
    ]
