# Railway deployment configuration for MotoMundo
version = 1

[[services]]
name = "motomundo"
source = "."

[services.build]
buildCommand = "pip install -r requirements.txt"

[services.deploy]
startCommand = "./start.sh"
healthcheckPath = "/health/"
