# Generated by Django 5.2.5 on 2025-08-22 18:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_transfer_data_from_clubs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('name', 'country')},
        ),
        migrations.AddField(
            model_name='country',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Country boundaries', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='country',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Central point of country', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='state',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='State boundaries', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='state',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Central point of state', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(help_text='ISO 3166-1 alpha-2 code', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, help_text='State/province code', max_length=10),
        ),
    ]
