# Generated by Django 5.2.5 on 2025-08-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_created_at_club_foundation_date_club_logo_and_more'),
        ('clubs', '0003_member'),
    ]

    operations = [
    ]
