# Generated by Django 5.2.5 on 2025-08-11
from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_member_split_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(
                Lower('first_name'), Lower('last_name'), 'chapter',
                name='uq_member_chapter_fullname_ci'
            ),
        ),
    ]
