# Generated by Django 5.2.5 on 2025-08-11 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_member_unique_name_ci'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
    ]
