# Generated by Django 5.2.5 on 2025-08-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_member_options_alter_member_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('rider', 'Rider')], max_length=30),
        ),
    ]
