# Generated by Django 5.2.5 on 2025-08-13 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_chaptermanager_clubadmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['chapter__club__name', 'chapter__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserClubContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Club Context',
                'verbose_name_plural': 'User Club Contexts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='chaptermanager',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chaptermanager',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='chaptermanager',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='chaptermanager',
            name='user',
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Link to a registered user, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'chapter'), name='uq_user_chapter_membership'),
        ),
        migrations.AddField(
            model_name='chapteradmin',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='clubs.chapter'),
        ),
        migrations.AddField(
            model_name='chapteradmin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chapter_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapteradmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_admin_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userclubcontext',
            name='active_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AddField(
            model_name='userclubcontext',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_club_context', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChapterManager',
        ),
        migrations.AlterUniqueTogether(
            name='chapteradmin',
            unique_together={('user', 'chapter')},
        ),
    ]
