# Generated by Django 5.2.5 on 2025-08-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_multi_club_membership_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('pilot', 'Pilot'), ('copilot', 'Copilot'), ('prospect', 'Prospect')], default='pilot', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='national_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='members/profiles/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('road_captain', 'Road Captain'), ('sergeant_at_arms', 'Sergeant at Arms'), ('rider', 'Rider'), ('member', 'Member')], max_length=30),
        ),
    ]
