# Generated by Django 5.2.5 on 2025-08-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_member_member_type_member_national_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('road_captain', 'Road Captain'), ('sergeant_at_arms', 'Sergeant at Arms'), ('member', 'Member')], max_length=30),
        ),
    ]
