# Generated by Django 5.2.5 on 2025-08-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_remove_rider_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='national_role',
            field=models.CharField(blank=True, choices=[('', '-- Sin rol nacional --'), ('zone_vp_south', 'Zone Vice President South'), ('zone_vp_center', 'Zone Vice President Center'), ('zone_vp_north', 'Zone Vice President North')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('member', 'Member')], max_length=30),
        ),
    ]
