# Generated by Django 5.2.5 on 2025-08-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_update_member_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='national_role',
            field=models.CharField(blank=True, choices=[('', '-- Sin rol nacional --'), ('national_president', 'National President'), ('national_vice_president', 'National Vice President'), ('national_secretary', 'National Secretary'), ('zone_vp_south', 'Zone Vice President South'), ('zone_vp_center', 'Zone Vice President Center'), ('zone_vp_north', 'Zone Vice President North')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('road_captain', 'Road Captain'), ('sergeant_at_arms', 'Sergeant at Arms'), ('member', 'Member')], max_length=30),
        ),
    ]
