# Generated by Django 5.2.5 on 2025-08-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_fix_national_roles_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='national_role',
            field=models.CharField(blank=True, choices=[('', '-- Sin rol nacional --'), ('national_president', 'National President'), ('national_vice_president', 'National Vice President'), ('national_secretary', 'National Secretary'), ('national_counselor', 'National Counselor'), ('zone_vp_south', 'Zone Vice President South'), ('zone_vp_center', 'Zone Vice President Center'), ('zone_vp_north', 'Zone Vice President North')], default='', max_length=50),
        ),
    ]
