# Generated by Django 5.2.5 on 2025-08-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_add_national_counselor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, help_text='Club logo - automatically optimized and stored in the cloud', null=True, upload_to='clubs/logos/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(help_text='Member profile picture - automatically optimized and stored in the cloud', upload_to='members/profiles/'),
        ),
    ]
