# Generated by Django 5.2.5 on 2025-08-16 19:24

import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_alter_club_logo_alter_member_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, help_text='Club logo - automatically optimized and stored in the cloud', null=True, storage=clubs.models.get_image_storage, upload_to='clubs/logos/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(help_text='Member profile picture - automatically optimized and stored in the cloud', storage=clubs.models.get_image_storage, upload_to='members/profiles/'),
        ),
    ]
