# Generated by Django 5.2.5 on 2025-08-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_alter_club_logo_alter_member_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='claim_code',
            field=models.CharField(blank=True, help_text='Unique code that allows a user to claim this member profile', max_length=50, null=True, unique=True),
        ),
    ]
