# Generated by Django 5.2.5 on 2025-08-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_add_discovery_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO country code (e.g., MX, US, CA)', max_length=3, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='club',
            name='country_new',
            field=models.ForeignKey(blank=True, help_text='Country where this club is primarily located', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.country'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text='State/Province code', max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='clubs.country')),
            ],
            options={
                'ordering': ['country__name', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='state_new',
            field=models.ForeignKey(blank=True, help_text='State where this chapter is located', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.state'),
        ),
        migrations.AddField(
            model_name='chapterjoinrequest',
            name='state_new',
            field=models.ForeignKey(blank=True, help_text='State where the chapter will be located', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.state'),
        ),
        migrations.AddField(
            model_name='club',
            name='primary_state_new',
            field=models.ForeignKey(blank=True, help_text='Primary state where this club is located', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.state'),
        ),
    ]
