# Generated by Django 5.2.5 on 2025-08-22 19:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0022_populate_mexico_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic coordinates for map display', null=True, srid=4326),
        ),
    ]
