# Generated by Django - Custom migration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0024_migrate_to_geography_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional member metadata'),
        ),
    ]
